---
roles:
  - name: geerlingguy.docker
    version: 7.1.0

  - name: geerlingguy.nfs
    version: 2.0.0

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: https://github.com/vladgh/ansible-collection-vladgh-samba
    version: main
    type: git
